---
# Domain
domain: test.voicenotes.space
certbot_email: dannygam47@gmail.com

# Service addresses (for containers use host.docker.internal)
db_host: host.docker.internal
db_port: 5432
db_name: BookDB
db_user: danny

api_host: host.docker.internal
api_port: 3000

# Docker
docker_users:
  - "{{ ansible_user }}"

# Certbot
certbot_install_method: snap
certbot_auto_renew: true
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_create_if_missing: true
certbot_certs:
  - domains:
      - "{{ domain }}"
