services:
  book-api:
    image: book-api
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:3000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://0.0.0.0:3000"
      ConnectionStrings__DefaultConnection: Host=db; Port=5432; Database = BookDB; Trust Server Certificate = true; Username=danny; Password=${DB_PASS}
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "danny"
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: "BookDB"