services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
    command: certonly --standalone --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}